name: classchronicaladminweb
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  firebase_auth: ^4.16.0
  firebase_core: ^2.24.2
  responsive_framework: ^1.0.0
  cloud_firestore: ^4.14.0
  uuid: ^4.1.0
  intl: ^0.18.1
  flutter_animated_dialog: ^2.0.1
  firebase_storage: ^11.6.0
  images_picker: ^1.2.11
  file_picker: ^5.3.1
  provider: ^6.1.1
  # cherry_toast: ^1.8.0
  shimmer: ^3.0.0
  flutter_svg: ^1.1.6
  image_picker: ^1.0.2
  firebase_messaging: ^14.7.10
  flutter_local_notifications: ^16.3.2
  path_provider: ^2.1.0
  http: ^0.13.5
  app_settings: ^4.3.1
  flutter_styled_toast: ^2.2.1


dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/png/
  

